<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-POD63J8" failures="0" tests="60" name="Tests.AirbnbTests1" time="4.415" errors="10" timestamp="2020-12-08T18:09:12 IST" skipped="50">
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.261">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:43)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test20" time="0.000">
    <skipped/>
  </testcase> <!-- test20 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.551">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:39)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at java.base/java.net.URL.<init>(URL.java:585)
... 23 more
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test24" time="0.000">
    <skipped/>
  </testcase> <!-- test24 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test2" time="0.000">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.215">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:43)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.841">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:39)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at java.base/java.net.URL.<init>(URL.java:585)
... 23 more
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test5" time="0.000">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test17" time="0.000">
    <skipped/>
  </testcase> <!-- test17 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test18" time="0.000">
    <skipped/>
  </testcase> <!-- test18 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test14" time="0.000">
    <skipped/>
  </testcase> <!-- test14 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test10" time="0.000">
    <skipped/>
  </testcase> <!-- test10 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test13" time="0.000">
    <skipped/>
  </testcase> <!-- test13 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test15" time="0.000">
    <skipped/>
  </testcase> <!-- test15 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test2" time="0.000">
    <skipped/>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test7" time="0.000">
    <skipped/>
  </testcase> <!-- test7 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test21" time="0.000">
    <skipped/>
  </testcase> <!-- test21 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test15" time="0.000">
    <skipped/>
  </testcase> <!-- test15 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.150">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:43)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test16" time="0.000">
    <skipped/>
  </testcase> <!-- test16 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test23" time="0.000">
    <skipped/>
  </testcase> <!-- test23 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.048">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:43)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test25" time="0.000">
    <skipped/>
  </testcase> <!-- test25 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test19" time="0.000">
    <skipped/>
  </testcase> <!-- test19 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.888">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:39)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test10" time="0.000">
    <skipped/>
  </testcase> <!-- test10 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test1" time="0.000">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test1" time="0.000">
    <skipped/>
  </testcase> <!-- test1 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.083">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:43)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test22" time="0.000">
    <skipped/>
  </testcase> <!-- test22 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test8" time="0.000">
    <skipped/>
  </testcase> <!-- test8 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test22" time="0.000">
    <skipped/>
  </testcase> <!-- test22 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test20" time="0.000">
    <skipped/>
  </testcase> <!-- test20 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test16" time="0.000">
    <skipped/>
  </testcase> <!-- test16 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test14" time="0.000">
    <skipped/>
  </testcase> <!-- test14 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test19" time="0.000">
    <skipped/>
  </testcase> <!-- test19 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test5" time="0.000">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test4" time="0.000">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test11" time="0.000">
    <skipped/>
  </testcase> <!-- test11 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test24" time="0.000">
    <skipped/>
  </testcase> <!-- test24 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test8" time="0.000">
    <skipped/>
  </testcase> <!-- test8 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.657">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:39)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at java.base/java.net.URL.<init>(URL.java:585)
... 23 more
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test18" time="0.000">
    <skipped/>
  </testcase> <!-- test18 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test23" time="0.000">
    <skipped/>
  </testcase> <!-- test23 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test25" time="0.000">
    <skipped/>
  </testcase> <!-- test25 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test17" time="0.000">
    <skipped/>
  </testcase> <!-- test17 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="LaunchApplication" time="0.721">
    <error type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at testBase.BrowserFactory.createBrowserInstance(BrowserFactory.java:39)
at testBase.TestBase.LaunchApplication(TestBase.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:523)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at java.base/java.net.URL.<init>(URL.java:585)
... 23 more
]]>
    </error>
  </testcase> <!-- LaunchApplication -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test11" time="0.000">
    <skipped/>
  </testcase> <!-- test11 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test7" time="0.000">
    <skipped/>
  </testcase> <!-- test7 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test13" time="0.000">
    <skipped/>
  </testcase> <!-- test13 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test4" time="0.000">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test21" time="0.000">
    <skipped/>
  </testcase> <!-- test21 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test3">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test3">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test9">
    <skipped/>
  </testcase> <!-- test9 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test9">
    <skipped/>
  </testcase> <!-- test9 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test12">
    <skipped/>
  </testcase> <!-- test12 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test6">
    <skipped/>
  </testcase> <!-- test6 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test12">
    <skipped/>
  </testcase> <!-- test12 -->
  <system-out/>
  <testcase classname="Tests.AirbnbTests1" name="test6">
    <skipped/>
  </testcase> <!-- test6 -->
  <system-out/>
</testsuite> <!-- Tests.AirbnbTests1 -->
